# .github/workflows/push.yml
name: Push to Replicate

on:
  push:
    branches:
      - main


jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Освободить место
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true

      - name: Клонировать репозиторий
        uses: actions/checkout@v4

      - name: Установить Cog и залогиниться
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_CLI_AUTH_TOKEN }}

      - name: Пуш модели
        run: cog push r8.im/barashov/replicate-test-model
